### PR TITLE
feat: upgrade the base container to use python 3.8 and ubuntu 22.04

### PR DESCRIPTION
**Pull request by math411**
*Issue #, if available:*

*Description of changes:*

Note, other containers will be updated to include the dependencies listed here pulled in from `pip`. This is its own PR as it is an upgrade to the base image in addition to the dependencies.

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [ ] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-containers/blob/main/CONTRIBUTING.md) doc
- [ ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-containers/blob/main/CONTRIBUTING.md#commit-your-change)
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-braket-containers/blob/main/README.md) and [API docs](https://github.com/aws/amazon-braket-containers/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by shpface** [comment]
Thanks. Could you remove the logs from the PR? Should the other frameworks have their versions of Braket libraries bumped to match base?

**Comment by math411** [comment]
> Thanks. Could you remove the logs from the PR? Should the other frameworks have their versions of Braket libraries bumped to match base?

Removed and added to .gitignore. There is a comment in the description covering that those will be in separate PRs

**Review by speller26 — APPROVED** [review]

**Review by shpface — APPROVED** [review]
> There is a comment in the description covering that those will be in separate PRs

Sorry, I missed that. The tensorflow is also based on ubuntu 18.04 and will need an update. Should it be included?

**Comment by math411** [comment]
> > There is a comment in the description covering that those will be in separate PRs
> 
> Sorry, I missed that. The tensorflow is also based on ubuntu 18.04 and will need an update. Should it be included?

In this case, I wanted to keep the PRs separate to limit the scopes of the PRs. Upgrading the base images used for each container, I felt it would be appropriate to give each their own PR.

**Pull request merged**
